#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sys/delay.h>
#include <sys/serial.h>
#include <sys/dcclog.h>
#include <sys/shell.h>
#include <sys/null.h>

#include "config.h"
#include "board.h"
#include "isink.h"
#include "slcdev.h"
#include "serdrv.h"
#include "xmodem.h"

#define VERSION_NUM "0.9"
#define VERSION_DATE "Jul, 2015"

extern const struct shell_cmd cmd_tab[];

extern const char version_str[];
extern const char copyright_str[];

void __attribute__((noreturn)) io_event_task(void);
void lamp_test(void);

uint32_t __attribute__((aligned(8))) io_event_stack[24];
uint32_t __attribute__((aligned(8))) sim_event_stack[96];

int js(FILE * f, char * script, unsigned int len);

void simlnk_task(void);

void board_test(void)
{
	FILE * f;

#ifndef DEBUG
	/* wait for the device to charge a little bit before enabling
	   peripherals */
	thinkos_sleep(2000);
#endif

	DCC_LOG(LOG_TRACE, "5. isink_init()");

	/* enable the current sink driver. This will start the negative 
	   voltage power supply */
	isink_init();

	/* configure the current sink driver to default values */
	isink_mode_set(ISINK_CURRENT_NOM | ISINK_RATE_FAST);
	/* dummy pulse to reset the timer */
	isink_pulse(2, 0);

	/* create a thread to handle IO events like switches and
	   address selection. This thread also controls the LEDs flashing. */
	thinkos_thread_create((void *)io_event_task, (void *)NULL,
						  io_event_stack, sizeof(io_event_stack) |
						  THINKOS_OPT_PRIORITY(1) | THINKOS_OPT_ID(1));

	DCC_LOG(LOG_TRACE, "6. lamp_test()");
	/* perform a lamp test while the current sink 
	   negative voltage stabilizes */
	lamp_test();

	DCC_LOG(LOG_TRACE, "7. slcdev_init()");
	/* initilice the SLC device driver */
	slcdev_init();

	DCC_LOG(LOG_TRACE, "8. const_strbuf_init()");
	/* initialize constat string buffer */
	const_strbuf_init();

	DCC_LOG(LOG_TRACE, "9. device_db_init()");
	/* initializes database */
	device_db_init();

	DCC_LOG(LOG_TRACE, "10. config_load()");
	/* load configuration */
	config_load();

	DCC_LOGSTR(LOG_TRACE, "\"%s\"", version_str);

	/* create a thread to handle simulation events. This is the 
	   actual simulation loop. The events are generated by the 
	   SLC device driver according to the configuration devices which 
	   are current enabled. */
	thinkos_thread_create((void *)sim_event_task, (void *)NULL,
						  sim_event_stack, sizeof(sim_event_stack) | 
						  THINKOS_OPT_PRIORITY(0) | THINKOS_OPT_ID(0));

	f = null_fopen(NULL);

	/* initialize STDIO */
	stdout = f;
	stderr = f;

	DCC_LOG1(LOG_TRACE, "f=%08x", f);
	fprintf(f, "\n%s\n%s\n\n", version_str, copyright_str);

	/* start simulation */
	thinkos_ev_raise(SLCDEV_DRV_EV, SLC_EV_SIM_START);

	simlnk_task();
}

