#
# Copyright(C) 2012 Robinson Mittmann. All Rights Reserved.
# 
# This file is part of the YARD-ICE.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You can receive a copy of the GNU Lesser General Public License from 
# http://www.gnu.org/

#
# File:   Makefile
# Author: Robinson Mittmann <bobmittmann@gmail.com>
# 

include ../../mk/config.mk

LIB_STATIC = cmd

CFILES = show_asm.c cmd_beep.c \
	  cmd_breakpoint.c cmd_connect.c \
	  cmd_dint.c cmd_disassemble.c cmd_eint.c \
	  cmd_goto.c cmd_halt.c cmd_init.c cmd_release.c \
	  cmd_reset.c cmd_run.c cmd_show_context.c cmd_mem_read.c \
	  cmd_step.c cmd_target.c cmd_version.c cmd_meminfo.c \
	  cmd_watchpoint.c cmd_mem_write.c cmd_mem_erase.c cmd_help.c \
	  cmd_let.c cmd_info.c cmd_probe.c \
	  cmd_tcp_rcv.c cmd_tcp_snd.c cmd_trst.c cmd_nrst.c cmd_tap.c \
	  cmd_power.c cmd_irscan.c cmd_drscan.c cmd_idcode.c \
	  cmd_var.c cmd_ice_test.c cmd_test.c\
	  cmd_ice_info.c cmd_bb_scan.c cmd_runtest.c \
	  cmd_irpause.c cmd_drpause.c cmd_i2c.c cmd_en_dis.c \
	  cmd_trace.c cmd_relay.c cmd_scrub.c \
	  cmd_fpga.c cmd_xflash.c otg_xflash_pic.c \
	  uart_xflash_pic.c xflash.c

include ../../mk/lib.mk

