#
# File:		Makefile
# Module:	
# Project:	
# Author:	Robinson Mittmann (bob@boreste.com, bobmittmann@gmail.com)
# Target:	
# Comment:
# Copyright(c) 2005-2009 BORESTE (www.boreste.com). All Rights Reserved.

PROJECT	= libhttpd

CFILES = 200.c 400.c 401.c 403.c 404.c 405.c 408.c 409.c 410.c \
		 411.c 413.c 414.c 415.c 500.c 501.c 503.c 505.c \
		 base64.c dirlist.c get.c httpd.c nvparse.c post.c 
#	auth.c init.c respond.c send.c start.c stop.c

CDEFS = 

include ../../tools/lib.mk

