#
# Copyright(C) 2012 Robinson Mittmann. All Rights Reserved.
# 
# This file is part of the YARD-ICE.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You can receive a copy of the GNU Lesser General Public License from 
# http://www.gnu.org/

#
# File:   Makefile
# Author: Robinson Mittmann <bobmittmann@gmail.com>
# 

LIB_STATIC = nand

CFILES = mod_nand.c nand-bb-check.c nand-block-erase.c\
		 nand-chip-init.c nand-chip-probe.c nand-dev.c\
		 nand-mem-map.c\
		 nand-page-read.c nand-page-write.c\
		 nand-spare-read.c nand-spare-write.c

include ../../mk/lib.mk

