-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.1.112
-- Module  Version: 5.8
--C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_phy -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type iol -mode mem -io_type SSTL25_I -freq_in 100 -dqs 1 8 -dqs 2 8 -sensitivity low -num_clk 1 -num_ce 1 -addr_width 13 -bank_width 2 -num_cs 2 

-- Thu Apr 19 10:11:02 2018

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity ddr_phy is
    port (
        burstdet0: out  std_logic; 
        burstdet1: out  std_logic; 
        casn: out  std_logic; 
        casn_din: in  std_logic; 
        datatri_0: in  std_logic; 
        datatri_1: in  std_logic; 
        datavalid_0: out  std_logic; 
        datavalid_1: out  std_logic; 
        dqs_0: inout  std_logic; 
        dqs_1: inout  std_logic; 
        dqso_0: in  std_logic; 
        dqso_1: in  std_logic; 
        dqstri_0: in  std_logic; 
        dqstri_1: in  std_logic; 
        freeze: in  std_logic; 
        lock: out  std_logic; 
        rasn: out  std_logic; 
        rasn_din: in  std_logic; 
        read_0: in  std_logic; 
        read_1: in  std_logic; 
        readclksel0_0: in  std_logic; 
        readclksel0_1: in  std_logic; 
        readclksel1_0: in  std_logic; 
        readclksel1_1: in  std_logic; 
        reset: in  std_logic; 
        sclk: in  std_logic; 
        uddcntln: in  std_logic; 
        wen: out  std_logic; 
        wen_din: in  std_logic; 
        addr: out  std_logic_vector(12 downto 0); 
        addr_din: in  std_logic_vector(12 downto 0); 
        ba: out  std_logic_vector(1 downto 0); 
        ba_din: in  std_logic_vector(1 downto 0); 
        cke: out  std_logic_vector(0 downto 0); 
        cke_din: in  std_logic_vector(0 downto 0); 
        csn: out  std_logic_vector(1 downto 0); 
        csn_din: in  std_logic_vector(1 downto 0); 
        datain0: out  std_logic_vector(15 downto 0); 
        datain1: out  std_logic_vector(15 downto 0); 
        dataout0: in  std_logic_vector(15 downto 0); 
        dataout1: in  std_logic_vector(15 downto 0); 
        ddrclk: out  std_logic_vector(0 downto 0); 
        dq_0: inout  std_logic_vector(7 downto 0); 
        dq_1: inout  std_logic_vector(7 downto 0));
end ddr_phy;

architecture Structure of ddr_phy is

    -- internal signal declarations
    signal buf_ckeo0: std_logic;
    signal buf_csno1: std_logic;
    signal buf_csno0: std_logic;
    signal buf_weno: std_logic;
    signal buf_casno: std_logic;
    signal buf_rasno: std_logic;
    signal buf_bao1: std_logic;
    signal buf_bao0: std_logic;
    signal buf_addro12: std_logic;
    signal buf_addro11: std_logic;
    signal buf_addro10: std_logic;
    signal buf_addro9: std_logic;
    signal buf_addro8: std_logic;
    signal buf_addro7: std_logic;
    signal buf_addro6: std_logic;
    signal buf_addro5: std_logic;
    signal buf_addro4: std_logic;
    signal buf_addro3: std_logic;
    signal buf_addro2: std_logic;
    signal buf_addro1: std_logic;
    signal buf_addro0: std_logic;
    signal buf_clkout0: std_logic;
    signal scuba_vhi: std_logic;
    signal sclk90: std_logic;
    signal scuba_vlo: std_logic;
    signal dqsw90_1: std_logic;
    signal dqsr90_1: std_logic;
    signal ddrclkpol1: std_logic;
    signal dqsw90_0: std_logic;
    signal dqsr90_0: std_logic;
    signal ddrclkpol0: std_logic;
    signal dqsdel: std_logic;
    signal db15: std_logic;
    signal db14: std_logic;
    signal db13: std_logic;
    signal db12: std_logic;
    signal db11: std_logic;
    signal db10: std_logic;
    signal db9: std_logic;
    signal db8: std_logic;
    signal da15: std_logic;
    signal da14: std_logic;
    signal da13: std_logic;
    signal da12: std_logic;
    signal da11: std_logic;
    signal da10: std_logic;
    signal da9: std_logic;
    signal da8: std_logic;
    signal qb15: std_logic;
    signal qb14: std_logic;
    signal qb13: std_logic;
    signal qb12: std_logic;
    signal qb11: std_logic;
    signal qb10: std_logic;
    signal qb9: std_logic;
    signal qb8: std_logic;
    signal qa15: std_logic;
    signal qa14: std_logic;
    signal qa13: std_logic;
    signal qa12: std_logic;
    signal qa11: std_logic;
    signal qa10: std_logic;
    signal qa9: std_logic;
    signal qa8: std_logic;
    signal dqtri1: std_logic;
    signal dqo15: std_logic;
    signal dqo14: std_logic;
    signal dqo13: std_logic;
    signal dqo12: std_logic;
    signal dqo11: std_logic;
    signal dqo10: std_logic;
    signal dqo9: std_logic;
    signal dqo8: std_logic;
    signal datain_t15: std_logic;
    signal datain_t14: std_logic;
    signal datain_t13: std_logic;
    signal datain_t12: std_logic;
    signal datain_t11: std_logic;
    signal datain_t10: std_logic;
    signal datain_t9: std_logic;
    signal datain_t8: std_logic;
    signal buf_dq_1i7: std_logic;
    signal buf_dq_1t7: std_logic;
    signal buf_dq_1o7: std_logic;
    signal buf_dq_1i6: std_logic;
    signal buf_dq_1t6: std_logic;
    signal buf_dq_1o6: std_logic;
    signal buf_dq_1i5: std_logic;
    signal buf_dq_1t5: std_logic;
    signal buf_dq_1o5: std_logic;
    signal buf_dq_1i4: std_logic;
    signal buf_dq_1t4: std_logic;
    signal buf_dq_1o4: std_logic;
    signal buf_dq_1i3: std_logic;
    signal buf_dq_1t3: std_logic;
    signal buf_dq_1o3: std_logic;
    signal buf_dq_1i2: std_logic;
    signal buf_dq_1t2: std_logic;
    signal buf_dq_1o2: std_logic;
    signal buf_dq_1i1: std_logic;
    signal buf_dq_1t1: std_logic;
    signal buf_dq_1o1: std_logic;
    signal buf_dq_1i0: std_logic;
    signal buf_dq_1t0: std_logic;
    signal buf_dq_1o0: std_logic;
    signal dqsin1: std_logic;
    signal dqsout1: std_logic;
    signal dqstrio1: std_logic;
    signal buf_dqs_1i: std_logic;
    signal buf_dqs_1t: std_logic;
    signal buf_dqs_1o: std_logic;
    signal db7: std_logic;
    signal db6: std_logic;
    signal db5: std_logic;
    signal db4: std_logic;
    signal db3: std_logic;
    signal db2: std_logic;
    signal db1: std_logic;
    signal db0: std_logic;
    signal da7: std_logic;
    signal da6: std_logic;
    signal da5: std_logic;
    signal da4: std_logic;
    signal da3: std_logic;
    signal da2: std_logic;
    signal da1: std_logic;
    signal da0: std_logic;
    signal qb7: std_logic;
    signal qb6: std_logic;
    signal qb5: std_logic;
    signal qb4: std_logic;
    signal qb3: std_logic;
    signal qb2: std_logic;
    signal qb1: std_logic;
    signal qb0: std_logic;
    signal qa7: std_logic;
    signal qa6: std_logic;
    signal qa5: std_logic;
    signal qa4: std_logic;
    signal qa3: std_logic;
    signal qa2: std_logic;
    signal qa1: std_logic;
    signal qa0: std_logic;
    signal dqtri0: std_logic;
    signal dqo7: std_logic;
    signal dqo6: std_logic;
    signal dqo5: std_logic;
    signal dqo4: std_logic;
    signal dqo3: std_logic;
    signal dqo2: std_logic;
    signal dqo1: std_logic;
    signal dqo0: std_logic;
    signal datain_t7: std_logic;
    signal datain_t6: std_logic;
    signal datain_t5: std_logic;
    signal datain_t4: std_logic;
    signal datain_t3: std_logic;
    signal datain_t2: std_logic;
    signal datain_t1: std_logic;
    signal datain_t0: std_logic;
    signal buf_dq_0i7: std_logic;
    signal buf_dq_0t7: std_logic;
    signal buf_dq_0o7: std_logic;
    signal buf_dq_0i6: std_logic;
    signal buf_dq_0t6: std_logic;
    signal buf_dq_0o6: std_logic;
    signal buf_dq_0i5: std_logic;
    signal buf_dq_0t5: std_logic;
    signal buf_dq_0o5: std_logic;
    signal buf_dq_0i4: std_logic;
    signal buf_dq_0t4: std_logic;
    signal buf_dq_0o4: std_logic;
    signal buf_dq_0i3: std_logic;
    signal buf_dq_0t3: std_logic;
    signal buf_dq_0o3: std_logic;
    signal buf_dq_0i2: std_logic;
    signal buf_dq_0t2: std_logic;
    signal buf_dq_0o2: std_logic;
    signal buf_dq_0i1: std_logic;
    signal buf_dq_0t1: std_logic;
    signal buf_dq_0o1: std_logic;
    signal buf_dq_0i0: std_logic;
    signal buf_dq_0t0: std_logic;
    signal buf_dq_0o0: std_logic;
    signal dqsin0: std_logic;
    signal dqsout0: std_logic;
    signal dqstrio0: std_logic;
    signal buf_dqs_0i: std_logic;
    signal buf_dqs_0t: std_logic;
    signal buf_dqs_0o: std_logic;

    -- local component declarations
    component OFS1P3DX
        port (D: in  std_logic; SP: in  std_logic; SCLK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component BB
        port (I: in  std_logic; T: in  std_logic; O: out  std_logic; 
            B: inout  std_logic);
    end component;
    component OB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    component IDDRDQSX1A
        port (D: in  std_logic; DQSR90: in  std_logic; 
            DDRCLKPOL: in  std_logic; SCLK: in  std_logic; 
            RST: in  std_logic; Q0: out  std_logic; Q1: out  std_logic);
    end component;
    component ODDRXE
        port (D0: in  std_logic; D1: in  std_logic; SCLK: in  std_logic; 
            RST: in  std_logic; Q: out  std_logic);
    end component;
    component ODDRDQSX1A
        port (DQSW90: in  std_logic; SCLK: in  std_logic; 
            D0: in  std_logic; D1: in  std_logic; RST: in  std_logic; 
            Q: out  std_logic);
    end component;
    component TDDRA
        generic (DQSW90_INVERT : in String);
        port (DQSW90: in  std_logic; SCLK: in  std_logic; 
            TD: in  std_logic; RST: in  std_logic; TQ: out  std_logic);
    end component;
    component DQSBUFH
        generic (LPDDR : in String);
        port (SCLK: in  std_logic; DQSI: in  std_logic; 
            READ: in  std_logic; READCLKSEL1: in  std_logic; 
            READCLKSEL0: in  std_logic; RST: in  std_logic; 
            DQSDEL: in  std_logic; DDRCLKPOL: out  std_logic; 
            DQSR90: out  std_logic; DQSW90: out  std_logic; 
            DATAVALID: out  std_logic; BURSTDET: out  std_logic);
    end component;
    component DQSDLLC
        generic (FORCE_MAX_DELAY : in String; FIN : in String; 
                LOCK_SENSITIVITY : in String);
        port (CLK: in  std_logic; RST: in  std_logic; 
            UDDCNTLN: in  std_logic; FREEZE: in  std_logic; 
            LOCK: out  std_logic; DQSDEL: out  std_logic);
    end component;
    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst25_OB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst23_OB1 : label is "SSTL25_I";
    attribute IO_TYPE of Inst23_OB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst21_OB : label is "SSTL25_I";
    attribute IO_TYPE of Inst19_OB : label is "SSTL25_I";
    attribute IO_TYPE of Inst17_OB : label is "SSTL25_I";
    attribute IO_TYPE of Inst15_OB1 : label is "SSTL25_I";
    attribute IO_TYPE of Inst15_OB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB12 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB11 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB10 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB9 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB8 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB7 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB6 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB5 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB4 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB3 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB2 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB1 : label is "SSTL25_I";
    attribute IO_TYPE of Inst13_OB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst11_OB0 : label is "SSTL25D_I";
    attribute IO_TYPE of Inst4_BB7 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB6 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB5 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB4 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB3 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB2 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB1 : label is "SSTL25_I";
    attribute IO_TYPE of Inst4_BB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst3_BB : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB7 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB6 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB5 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB4 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB3 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB2 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB1 : label is "SSTL25_I";
    attribute IO_TYPE of Inst2_BB0 : label is "SSTL25_I";
    attribute IO_TYPE of Inst1_BB : label is "SSTL25_I";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst25_OB0: OB
        port map (I=>buf_ckeo0, O=>cke(0));

    Inst24_OFS1P3DX0: OFS1P3DX
        port map (D=>cke_din(0), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_ckeo0);

    Inst23_OB1: OB
        port map (I=>buf_csno1, O=>csn(1));

    Inst23_OB0: OB
        port map (I=>buf_csno0, O=>csn(0));

    Inst22_OFS1P3DX1: OFS1P3DX
        port map (D=>csn_din(1), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_csno1);

    Inst22_OFS1P3DX0: OFS1P3DX
        port map (D=>csn_din(0), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_csno0);

    Inst21_OB: OB
        port map (I=>buf_weno, O=>wen);

    Inst20_OFS1P3DX: OFS1P3DX
        port map (D=>wen_din, SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_weno);

    Inst19_OB: OB
        port map (I=>buf_casno, O=>casn);

    Inst18_OFS1P3DX: OFS1P3DX
        port map (D=>casn_din, SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_casno);

    Inst17_OB: OB
        port map (I=>buf_rasno, O=>rasn);

    Inst16_OFS1P3DX: OFS1P3DX
        port map (D=>rasn_din, SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_rasno);

    Inst15_OB1: OB
        port map (I=>buf_bao1, O=>ba(1));

    Inst15_OB0: OB
        port map (I=>buf_bao0, O=>ba(0));

    Inst14_OFS1P3DX1: OFS1P3DX
        port map (D=>ba_din(1), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_bao1);

    Inst14_OFS1P3DX0: OFS1P3DX
        port map (D=>ba_din(0), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_bao0);

    Inst13_OB12: OB
        port map (I=>buf_addro12, O=>addr(12));

    Inst13_OB11: OB
        port map (I=>buf_addro11, O=>addr(11));

    Inst13_OB10: OB
        port map (I=>buf_addro10, O=>addr(10));

    Inst13_OB9: OB
        port map (I=>buf_addro9, O=>addr(9));

    Inst13_OB8: OB
        port map (I=>buf_addro8, O=>addr(8));

    Inst13_OB7: OB
        port map (I=>buf_addro7, O=>addr(7));

    Inst13_OB6: OB
        port map (I=>buf_addro6, O=>addr(6));

    Inst13_OB5: OB
        port map (I=>buf_addro5, O=>addr(5));

    Inst13_OB4: OB
        port map (I=>buf_addro4, O=>addr(4));

    Inst13_OB3: OB
        port map (I=>buf_addro3, O=>addr(3));

    Inst13_OB2: OB
        port map (I=>buf_addro2, O=>addr(2));

    Inst13_OB1: OB
        port map (I=>buf_addro1, O=>addr(1));

    Inst13_OB0: OB
        port map (I=>buf_addro0, O=>addr(0));

    Inst12_OFS1P3DX12: OFS1P3DX
        port map (D=>addr_din(12), SP=>scuba_vhi, SCLK=>sclk90, 
            CD=>reset, Q=>buf_addro12);

    Inst12_OFS1P3DX11: OFS1P3DX
        port map (D=>addr_din(11), SP=>scuba_vhi, SCLK=>sclk90, 
            CD=>reset, Q=>buf_addro11);

    Inst12_OFS1P3DX10: OFS1P3DX
        port map (D=>addr_din(10), SP=>scuba_vhi, SCLK=>sclk90, 
            CD=>reset, Q=>buf_addro10);

    Inst12_OFS1P3DX9: OFS1P3DX
        port map (D=>addr_din(9), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro9);

    Inst12_OFS1P3DX8: OFS1P3DX
        port map (D=>addr_din(8), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro8);

    Inst12_OFS1P3DX7: OFS1P3DX
        port map (D=>addr_din(7), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro7);

    Inst12_OFS1P3DX6: OFS1P3DX
        port map (D=>addr_din(6), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro6);

    Inst12_OFS1P3DX5: OFS1P3DX
        port map (D=>addr_din(5), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro5);

    Inst12_OFS1P3DX4: OFS1P3DX
        port map (D=>addr_din(4), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro4);

    Inst12_OFS1P3DX3: OFS1P3DX
        port map (D=>addr_din(3), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro3);

    Inst12_OFS1P3DX2: OFS1P3DX
        port map (D=>addr_din(2), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro2);

    Inst12_OFS1P3DX1: OFS1P3DX
        port map (D=>addr_din(1), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro1);

    Inst12_OFS1P3DX0: OFS1P3DX
        port map (D=>addr_din(0), SP=>scuba_vhi, SCLK=>sclk90, CD=>reset, 
            Q=>buf_addro0);

    Inst11_OB0: OB
        port map (I=>buf_clkout0, O=>ddrclk(0));

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst10_ODDRXE0: ODDRXE
        port map (D0=>scuba_vlo, D1=>scuba_vhi, SCLK=>sclk90, RST=>reset, 
            Q=>buf_clkout0);

    Inst9_TDDRA1: TDDRA
        generic map (DQSW90_INVERT=> "ENABLED")
        port map (DQSW90=>sclk, SCLK=>sclk, TD=>dqstri_1, RST=>reset, 
            TQ=>dqstrio1);

    Inst9_TDDRA0: TDDRA
        generic map (DQSW90_INVERT=> "ENABLED")
        port map (DQSW90=>sclk, SCLK=>sclk, TD=>dqstri_0, RST=>reset, 
            TQ=>dqstrio0);

    Inst8_ODDRDQSX1A1: ODDRDQSX1A
        port map (DQSW90=>sclk, SCLK=>sclk, D0=>scuba_vlo, D1=>dqso_1, 
            RST=>reset, Q=>dqsout1);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    Inst8_ODDRDQSX1A0: ODDRDQSX1A
        port map (DQSW90=>sclk, SCLK=>sclk, D0=>scuba_vlo, D1=>dqso_0, 
            RST=>reset, Q=>dqsout0);

    Inst7_TDDRA1: TDDRA
        generic map (DQSW90_INVERT=> "DISABLED")
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, TD=>datatri_1, 
            RST=>reset, TQ=>dqtri1);

    Inst7_TDDRA0: TDDRA
        generic map (DQSW90_INVERT=> "DISABLED")
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, TD=>datatri_0, 
            RST=>reset, TQ=>dqtri0);

    Inst_ODDRDQSX1A_1_7: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da15, D1=>db15, 
            RST=>reset, Q=>dqo15);

    Inst_ODDRDQSX1A_1_6: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da14, D1=>db14, 
            RST=>reset, Q=>dqo14);

    Inst_ODDRDQSX1A_1_5: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da13, D1=>db13, 
            RST=>reset, Q=>dqo13);

    Inst_ODDRDQSX1A_1_4: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da12, D1=>db12, 
            RST=>reset, Q=>dqo12);

    Inst_ODDRDQSX1A_1_3: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da11, D1=>db11, 
            RST=>reset, Q=>dqo11);

    Inst_ODDRDQSX1A_1_2: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da10, D1=>db10, 
            RST=>reset, Q=>dqo10);

    Inst_ODDRDQSX1A_1_1: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da9, D1=>db9, 
            RST=>reset, Q=>dqo9);

    Inst_ODDRDQSX1A_1_0: ODDRDQSX1A
        port map (DQSW90=>dqsw90_1, SCLK=>sclk, D0=>da8, D1=>db8, 
            RST=>reset, Q=>dqo8);

    Inst_ODDRDQSX1A_0_7: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da7, D1=>db7, 
            RST=>reset, Q=>dqo7);

    Inst_ODDRDQSX1A_0_6: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da6, D1=>db6, 
            RST=>reset, Q=>dqo6);

    Inst_ODDRDQSX1A_0_5: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da5, D1=>db5, 
            RST=>reset, Q=>dqo5);

    Inst_ODDRDQSX1A_0_4: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da4, D1=>db4, 
            RST=>reset, Q=>dqo4);

    Inst_ODDRDQSX1A_0_3: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da3, D1=>db3, 
            RST=>reset, Q=>dqo3);

    Inst_ODDRDQSX1A_0_2: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da2, D1=>db2, 
            RST=>reset, Q=>dqo2);

    Inst_ODDRDQSX1A_0_1: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da1, D1=>db1, 
            RST=>reset, Q=>dqo1);

    Inst_ODDRDQSX1A_0_0: ODDRDQSX1A
        port map (DQSW90=>dqsw90_0, SCLK=>sclk, D0=>da0, D1=>db0, 
            RST=>reset, Q=>dqo0);

    Inst_IDDRDQSX1A_1_7: IDDRDQSX1A
        port map (D=>datain_t15, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa15, Q1=>qb15);

    Inst_IDDRDQSX1A_1_6: IDDRDQSX1A
        port map (D=>datain_t14, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa14, Q1=>qb14);

    Inst_IDDRDQSX1A_1_5: IDDRDQSX1A
        port map (D=>datain_t13, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa13, Q1=>qb13);

    Inst_IDDRDQSX1A_1_4: IDDRDQSX1A
        port map (D=>datain_t12, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa12, Q1=>qb12);

    Inst_IDDRDQSX1A_1_3: IDDRDQSX1A
        port map (D=>datain_t11, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa11, Q1=>qb11);

    Inst_IDDRDQSX1A_1_2: IDDRDQSX1A
        port map (D=>datain_t10, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa10, Q1=>qb10);

    Inst_IDDRDQSX1A_1_1: IDDRDQSX1A
        port map (D=>datain_t9, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa9, Q1=>qb9);

    Inst_IDDRDQSX1A_1_0: IDDRDQSX1A
        port map (D=>datain_t8, DQSR90=>dqsr90_1, DDRCLKPOL=>ddrclkpol1, 
            SCLK=>sclk, RST=>reset, Q0=>qa8, Q1=>qb8);

    Inst_IDDRDQSX1A_0_7: IDDRDQSX1A
        port map (D=>datain_t7, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa7, Q1=>qb7);

    Inst_IDDRDQSX1A_0_6: IDDRDQSX1A
        port map (D=>datain_t6, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa6, Q1=>qb6);

    Inst_IDDRDQSX1A_0_5: IDDRDQSX1A
        port map (D=>datain_t5, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa5, Q1=>qb5);

    Inst_IDDRDQSX1A_0_4: IDDRDQSX1A
        port map (D=>datain_t4, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa4, Q1=>qb4);

    Inst_IDDRDQSX1A_0_3: IDDRDQSX1A
        port map (D=>datain_t3, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa3, Q1=>qb3);

    Inst_IDDRDQSX1A_0_2: IDDRDQSX1A
        port map (D=>datain_t2, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa2, Q1=>qb2);

    Inst_IDDRDQSX1A_0_1: IDDRDQSX1A
        port map (D=>datain_t1, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa1, Q1=>qb1);

    Inst_IDDRDQSX1A_0_0: IDDRDQSX1A
        port map (D=>datain_t0, DQSR90=>dqsr90_0, DDRCLKPOL=>ddrclkpol0, 
            SCLK=>sclk, RST=>reset, Q0=>qa0, Q1=>qb0);

    Inst6_DQSBUFH1: DQSBUFH
        generic map (LPDDR=> "DISABLED")
        port map (SCLK=>sclk, DQSI=>dqsin1, READ=>read_1, 
            READCLKSEL1=>readclksel1_1, READCLKSEL0=>readclksel0_1, 
            RST=>reset, DQSDEL=>dqsdel, DDRCLKPOL=>ddrclkpol1, 
            DQSR90=>dqsr90_1, DQSW90=>dqsw90_1, DATAVALID=>datavalid_1, 
            BURSTDET=>burstdet1);

    Inst6_DQSBUFH0: DQSBUFH
        generic map (LPDDR=> "DISABLED")
        port map (SCLK=>sclk, DQSI=>dqsin0, READ=>read_0, 
            READCLKSEL1=>readclksel1_0, READCLKSEL0=>readclksel0_0, 
            RST=>reset, DQSDEL=>dqsdel, DDRCLKPOL=>ddrclkpol0, 
            DQSR90=>dqsr90_0, DQSW90=>dqsw90_0, DATAVALID=>datavalid_0, 
            BURSTDET=>burstdet0);

    Inst5_DQSDLLC: DQSDLLC
        generic map (FORCE_MAX_DELAY=> "NO", FIN=> "100.0", 
        LOCK_SENSITIVITY=> "LOW")
        port map (CLK=>sclk, RST=>reset, UDDCNTLN=>uddcntln, 
            FREEZE=>freeze, LOCK=>lock, DQSDEL=>dqsdel);

    Inst4_BB7: BB
        port map (I=>buf_dq_1o7, T=>buf_dq_1t7, O=>buf_dq_1i7, 
            B=>dq_1(7));

    Inst4_BB6: BB
        port map (I=>buf_dq_1o6, T=>buf_dq_1t6, O=>buf_dq_1i6, 
            B=>dq_1(6));

    Inst4_BB5: BB
        port map (I=>buf_dq_1o5, T=>buf_dq_1t5, O=>buf_dq_1i5, 
            B=>dq_1(5));

    Inst4_BB4: BB
        port map (I=>buf_dq_1o4, T=>buf_dq_1t4, O=>buf_dq_1i4, 
            B=>dq_1(4));

    Inst4_BB3: BB
        port map (I=>buf_dq_1o3, T=>buf_dq_1t3, O=>buf_dq_1i3, 
            B=>dq_1(3));

    Inst4_BB2: BB
        port map (I=>buf_dq_1o2, T=>buf_dq_1t2, O=>buf_dq_1i2, 
            B=>dq_1(2));

    Inst4_BB1: BB
        port map (I=>buf_dq_1o1, T=>buf_dq_1t1, O=>buf_dq_1i1, 
            B=>dq_1(1));

    Inst4_BB0: BB
        port map (I=>buf_dq_1o0, T=>buf_dq_1t0, O=>buf_dq_1i0, 
            B=>dq_1(0));

    Inst3_BB: BB
        port map (I=>buf_dqs_1o, T=>buf_dqs_1t, O=>buf_dqs_1i, B=>dqs_1);

    Inst2_BB7: BB
        port map (I=>buf_dq_0o7, T=>buf_dq_0t7, O=>buf_dq_0i7, 
            B=>dq_0(7));

    Inst2_BB6: BB
        port map (I=>buf_dq_0o6, T=>buf_dq_0t6, O=>buf_dq_0i6, 
            B=>dq_0(6));

    Inst2_BB5: BB
        port map (I=>buf_dq_0o5, T=>buf_dq_0t5, O=>buf_dq_0i5, 
            B=>dq_0(5));

    Inst2_BB4: BB
        port map (I=>buf_dq_0o4, T=>buf_dq_0t4, O=>buf_dq_0i4, 
            B=>dq_0(4));

    Inst2_BB3: BB
        port map (I=>buf_dq_0o3, T=>buf_dq_0t3, O=>buf_dq_0i3, 
            B=>dq_0(3));

    Inst2_BB2: BB
        port map (I=>buf_dq_0o2, T=>buf_dq_0t2, O=>buf_dq_0i2, 
            B=>dq_0(2));

    Inst2_BB1: BB
        port map (I=>buf_dq_0o1, T=>buf_dq_0t1, O=>buf_dq_0i1, 
            B=>dq_0(1));

    Inst2_BB0: BB
        port map (I=>buf_dq_0o0, T=>buf_dq_0t0, O=>buf_dq_0i0, 
            B=>dq_0(0));

    Inst1_BB: BB
        port map (I=>buf_dqs_0o, T=>buf_dqs_0t, O=>buf_dqs_0i, B=>dqs_0);

    sclk90 <= sclk;
    db15 <= dataout1(15);
    db14 <= dataout1(14);
    db13 <= dataout1(13);
    db12 <= dataout1(12);
    db11 <= dataout1(11);
    db10 <= dataout1(10);
    db9 <= dataout1(9);
    db8 <= dataout1(8);
    da15 <= dataout1(7);
    da14 <= dataout1(6);
    da13 <= dataout1(5);
    da12 <= dataout1(4);
    da11 <= dataout1(3);
    da10 <= dataout1(2);
    da9 <= dataout1(1);
    da8 <= dataout1(0);
    datain1(15) <= qb15;
    datain1(14) <= qb14;
    datain1(13) <= qb13;
    datain1(12) <= qb12;
    datain1(11) <= qb11;
    datain1(10) <= qb10;
    datain1(9) <= qb9;
    datain1(8) <= qb8;
    datain1(7) <= qa15;
    datain1(6) <= qa14;
    datain1(5) <= qa13;
    datain1(4) <= qa12;
    datain1(3) <= qa11;
    datain1(2) <= qa10;
    datain1(1) <= qa9;
    datain1(0) <= qa8;
    buf_dq_1t7 <= dqtri1;
    buf_dq_1t6 <= dqtri1;
    buf_dq_1t5 <= dqtri1;
    buf_dq_1t4 <= dqtri1;
    buf_dq_1t3 <= dqtri1;
    buf_dq_1t2 <= dqtri1;
    buf_dq_1t1 <= dqtri1;
    buf_dq_1t0 <= dqtri1;
    buf_dq_1o7 <= dqo15;
    buf_dq_1o6 <= dqo14;
    buf_dq_1o5 <= dqo13;
    buf_dq_1o4 <= dqo12;
    buf_dq_1o3 <= dqo11;
    buf_dq_1o2 <= dqo10;
    buf_dq_1o1 <= dqo9;
    buf_dq_1o0 <= dqo8;
    datain_t15 <= buf_dq_1i7;
    datain_t14 <= buf_dq_1i6;
    datain_t13 <= buf_dq_1i5;
    datain_t12 <= buf_dq_1i4;
    datain_t11 <= buf_dq_1i3;
    datain_t10 <= buf_dq_1i2;
    datain_t9 <= buf_dq_1i1;
    datain_t8 <= buf_dq_1i0;
    dqsin1 <= buf_dqs_1i;
    buf_dqs_1o <= dqsout1;
    buf_dqs_1t <= dqstrio1;
    db7 <= dataout0(15);
    db6 <= dataout0(14);
    db5 <= dataout0(13);
    db4 <= dataout0(12);
    db3 <= dataout0(11);
    db2 <= dataout0(10);
    db1 <= dataout0(9);
    db0 <= dataout0(8);
    da7 <= dataout0(7);
    da6 <= dataout0(6);
    da5 <= dataout0(5);
    da4 <= dataout0(4);
    da3 <= dataout0(3);
    da2 <= dataout0(2);
    da1 <= dataout0(1);
    da0 <= dataout0(0);
    datain0(15) <= qb7;
    datain0(14) <= qb6;
    datain0(13) <= qb5;
    datain0(12) <= qb4;
    datain0(11) <= qb3;
    datain0(10) <= qb2;
    datain0(9) <= qb1;
    datain0(8) <= qb0;
    datain0(7) <= qa7;
    datain0(6) <= qa6;
    datain0(5) <= qa5;
    datain0(4) <= qa4;
    datain0(3) <= qa3;
    datain0(2) <= qa2;
    datain0(1) <= qa1;
    datain0(0) <= qa0;
    buf_dq_0t7 <= dqtri0;
    buf_dq_0t6 <= dqtri0;
    buf_dq_0t5 <= dqtri0;
    buf_dq_0t4 <= dqtri0;
    buf_dq_0t3 <= dqtri0;
    buf_dq_0t2 <= dqtri0;
    buf_dq_0t1 <= dqtri0;
    buf_dq_0t0 <= dqtri0;
    buf_dq_0o7 <= dqo7;
    buf_dq_0o6 <= dqo6;
    buf_dq_0o5 <= dqo5;
    buf_dq_0o4 <= dqo4;
    buf_dq_0o3 <= dqo3;
    buf_dq_0o2 <= dqo2;
    buf_dq_0o1 <= dqo1;
    buf_dq_0o0 <= dqo0;
    datain_t7 <= buf_dq_0i7;
    datain_t6 <= buf_dq_0i6;
    datain_t5 <= buf_dq_0i5;
    datain_t4 <= buf_dq_0i4;
    datain_t3 <= buf_dq_0i3;
    datain_t2 <= buf_dq_0i2;
    datain_t1 <= buf_dq_0i1;
    datain_t0 <= buf_dq_0i0;
    dqsin0 <= buf_dqs_0i;
    buf_dqs_0o <= dqsout0;
    buf_dqs_0t <= dqstrio0;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of ddr_phy is
    for Structure
        for all:OFS1P3DX use entity MACHXO2.OFS1P3DX(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:BB use entity MACHXO2.BB(V); end for;
        for all:OB use entity MACHXO2.OB(V); end for;
        for all:IDDRDQSX1A use entity MACHXO2.IDDRDQSX1A(V); end for;
        for all:ODDRXE use entity MACHXO2.ODDRXE(V); end for;
        for all:ODDRDQSX1A use entity MACHXO2.ODDRDQSX1A(V); end for;
        for all:TDDRA use entity MACHXO2.TDDRA(V); end for;
        for all:DQSBUFH use entity MACHXO2.DQSBUFH(V); end for;
        for all:DQSDLLC use entity MACHXO2.DQSDLLC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
