-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
--C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n memctl -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type iol -mode in -io_type LVCMOS25 -width 32 -freq_in 166 -clk sclk -aligned -del -1 -gear 0 

-- Wed Apr 11 14:57:37 2018

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity memctl is
    port (
        clk: in  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        datain: in  std_logic_vector(31 downto 0); 
        q: out  std_logic_vector(31 downto 0));
end memctl;

architecture Structure of memctl is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal dataini_t31: std_logic;
    signal dataini_t30: std_logic;
    signal dataini_t29: std_logic;
    signal dataini_t28: std_logic;
    signal dataini_t27: std_logic;
    signal dataini_t26: std_logic;
    signal dataini_t25: std_logic;
    signal dataini_t24: std_logic;
    signal dataini_t23: std_logic;
    signal dataini_t22: std_logic;
    signal dataini_t21: std_logic;
    signal dataini_t20: std_logic;
    signal dataini_t19: std_logic;
    signal dataini_t18: std_logic;
    signal dataini_t17: std_logic;
    signal dataini_t16: std_logic;
    signal dataini_t15: std_logic;
    signal dataini_t14: std_logic;
    signal dataini_t13: std_logic;
    signal dataini_t12: std_logic;
    signal dataini_t11: std_logic;
    signal dataini_t10: std_logic;
    signal dataini_t9: std_logic;
    signal dataini_t8: std_logic;
    signal dataini_t7: std_logic;
    signal dataini_t6: std_logic;
    signal dataini_t5: std_logic;
    signal dataini_t4: std_logic;
    signal dataini_t3: std_logic;
    signal dataini_t2: std_logic;
    signal dataini_t1: std_logic;
    signal dataini_t0: std_logic;
    signal buf_clk: std_logic;
    signal buf_dataini31: std_logic;
    signal buf_dataini30: std_logic;
    signal buf_dataini29: std_logic;
    signal buf_dataini28: std_logic;
    signal buf_dataini27: std_logic;
    signal buf_dataini26: std_logic;
    signal buf_dataini25: std_logic;
    signal buf_dataini24: std_logic;
    signal buf_dataini23: std_logic;
    signal buf_dataini22: std_logic;
    signal buf_dataini21: std_logic;
    signal buf_dataini20: std_logic;
    signal buf_dataini19: std_logic;
    signal buf_dataini18: std_logic;
    signal buf_dataini17: std_logic;
    signal buf_dataini16: std_logic;
    signal buf_dataini15: std_logic;
    signal buf_dataini14: std_logic;
    signal buf_dataini13: std_logic;
    signal buf_dataini12: std_logic;
    signal buf_dataini11: std_logic;
    signal buf_dataini10: std_logic;
    signal buf_dataini9: std_logic;
    signal buf_dataini8: std_logic;
    signal buf_dataini7: std_logic;
    signal buf_dataini6: std_logic;
    signal buf_dataini5: std_logic;
    signal buf_dataini4: std_logic;
    signal buf_dataini3: std_logic;
    signal buf_dataini2: std_logic;
    signal buf_dataini1: std_logic;
    signal buf_dataini0: std_logic;

    -- local component declarations
    component IFS1P3DX
        port (D: in  std_logic; SP: in  std_logic; SCLK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component IB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst2_IB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB31 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB30 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB29 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB28 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB27 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB26 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB25 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB24 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB23 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB22 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB21 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB20 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB19 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB18 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB17 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB16 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB15 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB14 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB13 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB12 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB11 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB10 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB9 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB8 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB7 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB6 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB5 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB4 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB3 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB2 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB1 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst3_IFS1P3DX31: IFS1P3DX
        port map (D=>dataini_t31, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(31));

    Inst3_IFS1P3DX30: IFS1P3DX
        port map (D=>dataini_t30, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(30));

    Inst3_IFS1P3DX29: IFS1P3DX
        port map (D=>dataini_t29, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(29));

    Inst3_IFS1P3DX28: IFS1P3DX
        port map (D=>dataini_t28, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(28));

    Inst3_IFS1P3DX27: IFS1P3DX
        port map (D=>dataini_t27, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(27));

    Inst3_IFS1P3DX26: IFS1P3DX
        port map (D=>dataini_t26, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(26));

    Inst3_IFS1P3DX25: IFS1P3DX
        port map (D=>dataini_t25, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(25));

    Inst3_IFS1P3DX24: IFS1P3DX
        port map (D=>dataini_t24, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(24));

    Inst3_IFS1P3DX23: IFS1P3DX
        port map (D=>dataini_t23, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(23));

    Inst3_IFS1P3DX22: IFS1P3DX
        port map (D=>dataini_t22, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(22));

    Inst3_IFS1P3DX21: IFS1P3DX
        port map (D=>dataini_t21, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(21));

    Inst3_IFS1P3DX20: IFS1P3DX
        port map (D=>dataini_t20, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(20));

    Inst3_IFS1P3DX19: IFS1P3DX
        port map (D=>dataini_t19, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(19));

    Inst3_IFS1P3DX18: IFS1P3DX
        port map (D=>dataini_t18, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(18));

    Inst3_IFS1P3DX17: IFS1P3DX
        port map (D=>dataini_t17, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(17));

    Inst3_IFS1P3DX16: IFS1P3DX
        port map (D=>dataini_t16, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(16));

    Inst3_IFS1P3DX15: IFS1P3DX
        port map (D=>dataini_t15, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(15));

    Inst3_IFS1P3DX14: IFS1P3DX
        port map (D=>dataini_t14, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(14));

    Inst3_IFS1P3DX13: IFS1P3DX
        port map (D=>dataini_t13, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(13));

    Inst3_IFS1P3DX12: IFS1P3DX
        port map (D=>dataini_t12, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(12));

    Inst3_IFS1P3DX11: IFS1P3DX
        port map (D=>dataini_t11, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(11));

    Inst3_IFS1P3DX10: IFS1P3DX
        port map (D=>dataini_t10, SP=>scuba_vhi, SCLK=>buf_clk, 
            CD=>reset, Q=>q(10));

    Inst3_IFS1P3DX9: IFS1P3DX
        port map (D=>dataini_t9, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(9));

    Inst3_IFS1P3DX8: IFS1P3DX
        port map (D=>dataini_t8, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(8));

    Inst3_IFS1P3DX7: IFS1P3DX
        port map (D=>dataini_t7, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(7));

    Inst3_IFS1P3DX6: IFS1P3DX
        port map (D=>dataini_t6, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(6));

    Inst3_IFS1P3DX5: IFS1P3DX
        port map (D=>dataini_t5, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(5));

    Inst3_IFS1P3DX4: IFS1P3DX
        port map (D=>dataini_t4, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(4));

    Inst3_IFS1P3DX3: IFS1P3DX
        port map (D=>dataini_t3, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(3));

    Inst3_IFS1P3DX2: IFS1P3DX
        port map (D=>dataini_t2, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(2));

    Inst3_IFS1P3DX1: IFS1P3DX
        port map (D=>dataini_t1, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(1));

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst3_IFS1P3DX0: IFS1P3DX
        port map (D=>dataini_t0, SP=>scuba_vhi, SCLK=>buf_clk, CD=>reset, 
            Q=>q(0));

    Inst2_IB: IB
        port map (I=>clk, O=>buf_clk);

    Inst1_IB31: IB
        port map (I=>datain(31), O=>buf_dataini31);

    Inst1_IB30: IB
        port map (I=>datain(30), O=>buf_dataini30);

    Inst1_IB29: IB
        port map (I=>datain(29), O=>buf_dataini29);

    Inst1_IB28: IB
        port map (I=>datain(28), O=>buf_dataini28);

    Inst1_IB27: IB
        port map (I=>datain(27), O=>buf_dataini27);

    Inst1_IB26: IB
        port map (I=>datain(26), O=>buf_dataini26);

    Inst1_IB25: IB
        port map (I=>datain(25), O=>buf_dataini25);

    Inst1_IB24: IB
        port map (I=>datain(24), O=>buf_dataini24);

    Inst1_IB23: IB
        port map (I=>datain(23), O=>buf_dataini23);

    Inst1_IB22: IB
        port map (I=>datain(22), O=>buf_dataini22);

    Inst1_IB21: IB
        port map (I=>datain(21), O=>buf_dataini21);

    Inst1_IB20: IB
        port map (I=>datain(20), O=>buf_dataini20);

    Inst1_IB19: IB
        port map (I=>datain(19), O=>buf_dataini19);

    Inst1_IB18: IB
        port map (I=>datain(18), O=>buf_dataini18);

    Inst1_IB17: IB
        port map (I=>datain(17), O=>buf_dataini17);

    Inst1_IB16: IB
        port map (I=>datain(16), O=>buf_dataini16);

    Inst1_IB15: IB
        port map (I=>datain(15), O=>buf_dataini15);

    Inst1_IB14: IB
        port map (I=>datain(14), O=>buf_dataini14);

    Inst1_IB13: IB
        port map (I=>datain(13), O=>buf_dataini13);

    Inst1_IB12: IB
        port map (I=>datain(12), O=>buf_dataini12);

    Inst1_IB11: IB
        port map (I=>datain(11), O=>buf_dataini11);

    Inst1_IB10: IB
        port map (I=>datain(10), O=>buf_dataini10);

    Inst1_IB9: IB
        port map (I=>datain(9), O=>buf_dataini9);

    Inst1_IB8: IB
        port map (I=>datain(8), O=>buf_dataini8);

    Inst1_IB7: IB
        port map (I=>datain(7), O=>buf_dataini7);

    Inst1_IB6: IB
        port map (I=>datain(6), O=>buf_dataini6);

    Inst1_IB5: IB
        port map (I=>datain(5), O=>buf_dataini5);

    Inst1_IB4: IB
        port map (I=>datain(4), O=>buf_dataini4);

    Inst1_IB3: IB
        port map (I=>datain(3), O=>buf_dataini3);

    Inst1_IB2: IB
        port map (I=>datain(2), O=>buf_dataini2);

    Inst1_IB1: IB
        port map (I=>datain(1), O=>buf_dataini1);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= buf_clk;
    dataini_t31 <= buf_dataini31;
    dataini_t30 <= buf_dataini30;
    dataini_t29 <= buf_dataini29;
    dataini_t28 <= buf_dataini28;
    dataini_t27 <= buf_dataini27;
    dataini_t26 <= buf_dataini26;
    dataini_t25 <= buf_dataini25;
    dataini_t24 <= buf_dataini24;
    dataini_t23 <= buf_dataini23;
    dataini_t22 <= buf_dataini22;
    dataini_t21 <= buf_dataini21;
    dataini_t20 <= buf_dataini20;
    dataini_t19 <= buf_dataini19;
    dataini_t18 <= buf_dataini18;
    dataini_t17 <= buf_dataini17;
    dataini_t16 <= buf_dataini16;
    dataini_t15 <= buf_dataini15;
    dataini_t14 <= buf_dataini14;
    dataini_t13 <= buf_dataini13;
    dataini_t12 <= buf_dataini12;
    dataini_t11 <= buf_dataini11;
    dataini_t10 <= buf_dataini10;
    dataini_t9 <= buf_dataini9;
    dataini_t8 <= buf_dataini8;
    dataini_t7 <= buf_dataini7;
    dataini_t6 <= buf_dataini6;
    dataini_t5 <= buf_dataini5;
    dataini_t4 <= buf_dataini4;
    dataini_t3 <= buf_dataini3;
    dataini_t2 <= buf_dataini2;
    dataini_t1 <= buf_dataini1;
    dataini_t0 <= buf_dataini0;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of memctl is
    for Structure
        for all:IFS1P3DX use entity MACHXO2.IFS1P3DX(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:IB use entity MACHXO2.IB(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
