-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
-- Wed Apr 11 14:57:37 2018

-- parameterized module component declaration
component memctl
    port (clk: in  std_logic; reset: in  std_logic; sclk: out  std_logic; 
        datain: in  std_logic_vector(31 downto 0); 
        q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : memctl
    port map (clk=>__, reset=>__, sclk=>__, datain(31 downto 0)=>__, q(31 downto 0)=>__);
