-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
-- Wed Apr 11 15:02:45 2018

-- parameterized module component declaration
component sdram
    port (burstdet0: out  std_logic; datatri_0: in  std_logic; 
        datavalid_0: out  std_logic; dqs_0: inout  std_logic; 
        dqso_0: in  std_logic; dqstri_0: in  std_logic; 
        freeze: in  std_logic; lock: out  std_logic; 
        read_0: in  std_logic; readclksel0_0: in  std_logic; 
        readclksel1_0: in  std_logic; reset: in  std_logic; 
        sclk: in  std_logic; uddcntln: in  std_logic; 
        datain0: out  std_logic_vector(15 downto 0); 
        dataout0: in  std_logic_vector(15 downto 0); 
        dq_0: inout  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : sdram
    port map (burstdet0=>__, datatri_0=>__, datavalid_0=>__, dqs_0=>__, 
        dqso_0=>__, dqstri_0=>__, freeze=>__, lock=>__, read_0=>__, 
        readclksel0_0=>__, readclksel1_0=>__, reset=>__, sclk=>__, 
        uddcntln=>__, datain0(15 downto 0)=>__, dataout0(15 downto 0)=>__, 
        dq_0(7 downto 0)=>__);
