#
# Copyright(C) 2012 Robinson Mittmann. All Rights Reserved.
# 
# This file is part of the YARD-ICE.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You can receive a copy of the GNU Lesser General Public License from 
# http://www.gnu.org/

#
# File:   Makefile
# Author: Robinson Mittmann <bobmittmann@gmail.com>
# 


LIB_STATIC = shell

CFILES = readline.c parseline.c stripline.c shell.c exec.c \
		 cmd_date.c cmd_close.c cmd_ifconfig.c cmd_route.c \
		 cmd_arp.c cmd_ping.c cmd_netstat.c cmd_reboot.c \
		 cmd_memrd.c cmd_clear.c cmd_tcpstat.c 


include ../../mk/lib.mk
